# Generated by Django 4.2.4 on 2023-10-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='сгенерированный ключ'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='признак верификации'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ключ верификации'),
        ),
    ]
