# Generated by Django 4.2.4 on 2023-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(auto_created=150, blank=True, null=True, verbose_name='slug'),
        ),
    ]
